name: gpt_markdown
description: "Powerful Flutter Markdown & LaTeX Renderer: Rich Text, Math, Tables, Links, and Text Selection. Ideal for ChatGPT, Gemini, and more."
version: 1.1.0
homepage: https://github.com/Infinitix-LLC/gpt_markdown

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
        - asset: fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_18pt-Italic.ttf
          style: italic

topics:
  - markdown
  - latex
  - selectable
  - chatgpt
  - gemini

keywords:
  - flutter
  - markdown
  - flutter markdown
  - gpt
  - latex
  - chatgpt
  - rich text
  - ai
